version: '3.3'
services:
  drill:
    build: ./
    container_name: drill
    ports:
      - '8047:8047'
    tty: true
    #stdin_open: true
    networks:
      - main_network

    command: /bin/bash

networks:
  main_network:
    external: true
    name: main_network

